### ISSUE TITLE
The file doesn't exist

### ISSUE THREAD

**Issue by htmgarcia** [mebjas/jquery-shakker#1]
https://github.com/mebjas/jquery-shakker/blob/master/sample/index.html#L7

It should point to: jquery.shaker.min.js

**Comment by mebjas** [comment]
:D forgot to change,
thanks

**Comment by mebjas** [comment]
fixed https://github.com/mebjas/jquery-shakker/commit/46a91a193a6fcbbc91caec4aa191b40cd747a4f3

**Comment by htmgarcia** [comment]
Nice plugin! I wrote a post: https://www.ostraining.com/blog/coding/jquery-shakker/

**Comment by mebjas** [comment]
:D very interesting image used for demo! Its cool!
I recently wrote few other plugins which you might be interested in, like [`digital write`](https://github.com/mebjas/jquery-digitalwrite), [`image jigsaw`](https://github.com/mebjas/image-jigsaw), [`sticky elements`](https://github.com/mebjas/jQuery-sticky-elements)
